[package]
name = "duplicate_destroyer"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
id_tree = "1"
log = "0"
env_logger = "0"
blake2 = "0"
users = "0"
clap = { version = "4", features = ["derive"] }
regex = "1"
threadpool = "1"
serde = { version = "*", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempdir = "0.3"
mockall = "0.11"

[[bin]]
name = "duplicate_destroyer"
path = "src/main.rs"

[lib]
name = "duplicate_destroyer"
path = "src/lib.rs"
